config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :pictures do
    collection do
      post :confirm
    end
    member do
      patch :confirm
    end
  end

  resources :sessions, only: [:new, :create, :destroy]


  resources :users, only: [:new, :create, :show, :edit, :update]


  resources :favorites, only: [:create, :destroy, :index]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_picture, ImageUploader

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :profile_picture, presence: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :pictures
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]

  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def confirm
    # @picture = Picture.new(picture_params)
    # @picture.user_id = current_user.id
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def edit

    if User.find(@picture.user_id) != current_user
     redirect_to pictures_path
   end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def create
    # @picture = Picture.new(picture_params)
    # @picture.user_id = current_user.id
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
       PictureMailer.picture_mail(@picture).deliver

      redirect_to pictures_path, notice: "投稿が完了しました！"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "投稿が完了しました！"
    else
      render :edit
    end
  end

  def destroy
    if User.find(@picture.user_id) != current_user
     redirect_to pictures_path
    else
    @picture.destroy
     redirect_to pictures_url, notice: "削除しました！"
    end
  end

  private
    def set_picture
      @picture = Picture.find(params[:id])
    end

    def picture_params
      params.require(:picture).permit(:id, :image, :image_cache, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(params[:id])
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_picture, :profile_picture_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def form_choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      confirm_picture_path(@picture.id)
    end
  end

  def confirm_choose_new_or_edit
    if action_name == 'new'
      pictures_path
    elsif action_name == 'edit'
      picture_path(@picture.id)
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h1>お気に入り</h1>
<%= link_to '投稿一覧', pictures_path, class: 'btn btn-default' %>

<div class="table_scroll">
  <table>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= image_tag favorite.picture.image.url, size: '300x200' %></td>
        <td><%= favorite.picture.content%></td>
        <td><%= favorite.picture.user.name%></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <ul class="top_menu row">
          <% if logged_in? %>
            <li class="col-md-6 col-xs-6"><%= link_to "プロフィール", user_path(current_user.id) %></li>
            <li class="col-md-6 col-xs-6"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
          <% else %>
            <li class="col-md-6 col-xs-6"><%= link_to "新規登録", new_user_path %></li>
            <li class="col-md-6 col-xs-6"><%= link_to "ログイン", new_session_path %></li>
          <% end %>
        </ul>
    </header>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
    </div>
    <footer>
      <p>instagram clone</p>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url:form_choose_new_or_edit) do |form| %>

  <%= form.hidden_field :id %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>
      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">


    <table>
      <tr>
        <td><%= image_tag(picture.image.url) if picture.image && picture.image.url %></td>
      </tr>
      <tr>
        <td><%= form.text_area :content, size: "50x6" %></td>
      </tr>
      <tr>
        <td><%= form.file_field :image %></td>
      </tr>
      <tr>
        <td><%= form.hidden_field :image_cache %></td>
      </tr>
    </table>
  </div>

  <div class="actions">
    <%= form.submit "確認画面へ" %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h2>確認画面</h2>


<% if @picture.id.to_s == "" %>
  <%# 新規作成の場合 %>
  <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
    <table>
      <tr>
        <td><%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></td>
      </tr>
      <tr>
        <td><%= @picture.content%></td>
      </tr>
      <tr>
        <td><%= form.hidden_field :content %></td>
      </tr>
      <tr>
        <td><%= form.hidden_field :image_cache %></td>
      </tr>
      <tr>
        <td><%= form.submit "投稿する" %></td>
      </tr>
    </table>
  <% end %>

<% else %>
  <%# editで編集したい場合 %>
  <%= form_with(model: @picture, url: picture_path(@picture.id), local: true, method: :patch) do |form| %>
    <table>
      <tr>
        <td><%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></td>
      </tr>
      <tr>
        <td><%= @picture.content%></td>
      </tr>
      <tr>
        <td><%= form.hidden_field :content %></td>
      </tr>
      <tr>
        <td><%= form.hidden_field :image_cache %></td>
      </tr>
      <tr>
        <td><%= form.submit "投稿する" %></td>
      </tr>
    </table>
  <% end %>
<% end %>

<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<h1>編集画面</h1>
<%= render partial: 'form', locals: { picture: @picture } %>

<%= link_to '詳細', picture_path(@picture.id), class: 'btn btn-default' %> |
<%= link_to '一覧へ戻る', pictures_path, class: 'btn btn-default' %>

app/views/pictures/index.html.erb
<h2>投稿</h2>
<br>
<%= link_to '新規投稿', new_picture_path, class: 'btn btn-default' %>
<%= link_to 'お気に入り一覧', favorites_path, class: 'btn btn-default' %>

<div class="table_scroll">
  <table>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= image_tag picture.image.url %></td>
        <td><%= picture.content%></td>
        <td><%= picture.user.name%></td>
        <td><%= link_to '詳細', picture_path(picture.id), class: 'btn btn-default'  %></td>
        <td><%= link_to_if(User.find(picture.user_id) == current_user, '編集',
                           edit_picture_path(picture.id), class: 'btn btn-default'){} %></td>
        <td><%= link_to_if(User.find(picture.user_id) == current_user, '削除',
                          picture_path(picture.id), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-default'){} %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/pictures/new.html.erb
<h2>新規投稿</h2>
<br>
  <%= render partial: 'form', locals: { picture: @picture } %>
<br>
  <%= link_to '戻る', pictures_path, class: 'btn btn-default' %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @picture.image.url %>


<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>

    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-default' %>
  <% else %>

    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-default' %>
  <% end %>
<% end %>

<%= link_to_if(User.find(@picture.user_id) == current_user, '編集',
              edit_picture_path(@picture.id), class: 'btn btn-default'){} %>
<%= link_to '一覧へ戻る', pictures_path, class: 'btn btn-default' %>

app/views/users/edit.html.erb
<h4>プロフィール編集</h4>


<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, url:user_path(@user.id), local: true) do |form| %>
  <td><%= image_tag @user.profile_picture.url %></td>
  <table>
    <tr>
      <td><%= form.label :名前 %></td>
      <td><%= form.text_field :name %></td>
    </tr>
    <tr>
      <td><%= form.label :メールアドレス %></td>
      <td><%= form.email_field :email %></td>
    </tr>
    <tr>
      <td><%= form.label :パスワード %></td>
      <td><%= form.password_field :password %></td>
    </tr>
    <tr>
      <td><%= form.label :確認用パスワード %></td>
      <td><%= form.password_field :password_confirmation %></td>
    </tr>
    <tr>
      <td><%= form.label :プロフィール画像 %></td>
      <td><%= form.file_field :profile_picture %></td>
      <td><%= form.hidden_field :image_cache %></td>
    </tr>
  </table>

  <table>
    <tr>
      <td><%= form.submit "変更" %></td>
    </tr>
    <tr>
      <td><%= link_to '戻る', user_path(params[:id]), class: 'btn btn-default' %></td>
    </tr>
  </table>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %> 件のエラーがあります</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |form| %>
  <table>
    <tr>
      <td><%= form.label :名前 %></td>
      <td><%= form.text_field :name %></td>
    </tr>
    <tr>
      <td><%= form.label :メールアドレス %></td>
      <td><%= form.email_field :email %></td>
    </tr>
    <tr>
      <td><%= form.label :パスワード %></td>
      <td><%= form.password_field :password %></td>
    </tr>
    <tr>
      <td><%= form.label :確認用パスワード %></td>
      <td><%= form.password_field :password_confirmation %></td>
    </tr>
    <tr></tr>
    <tr>
      <td><%= form.label :プロフィール画像 %></td>
      <td><%= form.file_field :profile_picture %></td>
    </tr>
  </table>
  <%= form.submit "アカウントを作成する" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<br>
<%= image_tag @user.profile_picture.url %>
<table>
  <tr></tr>
  <tr>
    <td><%= link_to 'プロフィール編集', edit_user_path(@user.id), class: 'btn btn-default' %></td>
  </tr>
  <tr>
    <td><%= link_to '投稿一覧', pictures_path, class: 'btn btn-default' %></td>
  </tr>
</table>